"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.libs = void 0;
exports.libs = new Promise((resolve, _) => resolve([
    {
        Library_Name__c: "Jenny & Dan Keyser #2611 Saint Paul MN",
        Library_Geolocation__c: { latitude: 44.94366, longitude: -93.1694799 },
        Official_Charter_Number__c: "2611",
        Library_Story__c: "Dedicated to our mothers who loved to read.",
        Exact_Location_on_Map__c: true,
        Email_on_Map__c: false,
        Street__c: "1636 Ashland Ave",
        City__c: "Saint Paul",
        State_Province_Region__c: "MN",
        Country__c: "United States",
        Postal_Zip_Code__c: "55104",
        Id: "a060W00000wM3LOQA0",
    },
    {
        Library_Name__c: "Ann Cerkvenik #1398 Saint Paul MN",
        Library_Geolocation__c: { latitude: 44.9477, longitude: -93.12538 },
        List_As_Name__c: "Ann Cerkvenik",
        Official_Charter_Number__c: "1398",
        Library_Story__c: "This is dedicated to Rosemary Murphy who portrayed Maudie Atkinson in To Kill A Mockingbird which was one of the greatest books of all time. I dedicate this Little Free Library to her.",
        Exact_Location_on_Map__c: true,
        Email_on_Map__c: false,
        Street__c: "601 Dayton Ave",
        City__c: "Saint Paul",
        State_Province_Region__c: "MN",
        Country__c: "United States",
        Postal_Zip_Code__c: "55104",
        Id: "a06d000000b082IAAQ",
    },
    {
        Library_Name__c: "Matt Schneider #9262 Saint Paul MN",
        Library_Geolocation__c: { latitude: 44.9707099, longitude: -93.13515 },
        List_As_Name__c: "Matt Schneider",
        Primary_Steward_s_Email__c: "schn0440@gmail.com",
        Official_Charter_Number__c: "9262",
        Exact_Location_on_Map__c: true,
        Email_on_Map__c: true,
        Street__c: "978 Barrett",
        City__c: "Saint Paul",
        State_Province_Region__c: "MN",
        Country__c: "United States",
        Postal_Zip_Code__c: "55104",
        Id: "a06d000000b08A2AAI",
    },
    {
        Library_Name__c: "Anna Gremer #9971 St. Paul MN",
        Library_Geolocation__c: { latitude: 44.94682, longitude: -93.16978 },
        List_As_Name__c: "Anna Gremer",
        Official_Charter_Number__c: "9971",
        Library_Story__c: "This library is one of 20 donated to Little Brothers-Friends of the Elderly.",
        Exact_Location_on_Map__c: true,
        Email_on_Map__c: false,
        Street__c: "1645 Selby Ave",
        City__c: "St. Paul",
        State_Province_Region__c: "MN",
        Country__c: "United States",
        Postal_Zip_Code__c: "55104",
        Id: "a06d000000b08D6AAI",
    },
    {
        Library_Name__c: "Shane Zack #10274 St. Paul MN",
        Library_Geolocation__c: { latitude: 44.96479, longitude: -93.1584 },
        List_As_Name__c: "Shane Zack",
        Official_Charter_Number__c: "10274",
        Library_Story__c: "The plans for Friends Schoolâ??s Little Free Library started with parents Cathy Jordan and Fred Dulles, who saw how Little Free Libraryâ??s mission reflected that of Friends School of Minnesota. They set out to donate a little free library to the school as a parting gift when their last child graduated from Friends School. This started the conversation rolling and soon other parents jumped on board. A current parent Matt even offered to design and build our library. After months of conversation, planning and building, we installed our free little library at the front of the building. Every Little Free Library is special. It is great to see all the unique designs all over town. FSMâ??s library has some interesting features too: It was designed and built with a bench for sitting. It includes display slots where signage and artwork can be displayed and rotated throughout the year. The wood used to build the library is on its third life! It is redwood that was originally salvaged from an old deck. FSM science teacher Steve Moe rescued it and turned it into a picnic table, which we used for many years at the back of the school until one fateful night a plow truck flattened it. Steve saved the wood and when a parent needed lumber to build our Little Free Library, it was offered up. Matt planed, reshaped and fashioned it into the beautiful fixture we now have at the front of our building.",
        Exact_Location_on_Map__c: true,
        Email_on_Map__c: false,
        Street__c: "Friends School of Minnesota\n1365 Englewood Ave.",
        City__c: "St. Paul",
        State_Province_Region__c: "MN",
        Country__c: "United States",
        Postal_Zip_Code__c: "55104",
        Id: "a06d000000b08EiAAI",
    },
    {
        Library_Name__c: "Jon Gustafson #10846 St Paul MN",
        Library_Geolocation__c: { latitude: 44.95536, longitude: -93.17796 },
        List_As_Name__c: "Jon Gustafson",
        Primary_Steward_s_Email__c: "jgustafson@ehomesmn.org",
        Official_Charter_Number__c: "10846",
        Library_Story__c: "Episcopal Homes is the proud owner of a Little Free Library, located by Coventry Chapel's Meditation Garden and the Transitional Care Unit (TCU) Entrance! We hope you will â??take a book, return a bookâ?? when you visit your friends and loved ones. We are initially focusing on books that encourage a spirit of Wellness and Volunteerism. Our library is the result of an effort between AARP MNï»¿, Little Brothers - Friends of the Elderly, and Little Free Libraryï»¿ to reduce loneliness and isolation among older adults.",
        Exact_Location_on_Map__c: true,
        Email_on_Map__c: true,
        Street__c: "1840 University Ave W",
        City__c: "St Paul",
        State_Province_Region__c: "MN",
        Country__c: "United States",
        Postal_Zip_Code__c: "55104",
        Id: "a06d000000b08HqAAI",
    },
    {
        Library_Name__c: "Patrick Rhone Rhone #15837 Saint Paul MN",
        Library_Geolocation__c: { latitude: 44.9443, longitude: -93.12658 },
        List_As_Name__c: "Patrick Rhone Rhone",
        Official_Charter_Number__c: "15837",
        Library_Story__c: "Built this as an eighth wedding anniversary present for my Little Free Library loving wife. After being a recipient and benefactor of many books from other in the area, now she can give back.",
        Exact_Location_on_Map__c: true,
        Email_on_Map__c: false,
        Street__c: "627 Ashland Avenue",
        City__c: "Saint Paul",
        State_Province_Region__c: "MN",
        Country__c: "United States",
        Postal_Zip_Code__c: "55104",
        Id: "a06d000000b08XwAAI",
    },
    {
        Library_Name__c: "Debra Robison #4087 St. Paul MN",
        Library_Geolocation__c: { latitude: 44.94368, longitude: -93.15796 },
        Official_Charter_Number__c: "4087",
        Library_Story__c: "The library has enhanced an already close knit- connected neighborhood. Lots of participation since erected in late July! Loving it.",
        Exact_Location_on_Map__c: false,
        Email_on_Map__c: false,
        Id: "a06d000000bUpyvAAC",
    },
    {
        Library_Name__c: "Sharon Severson #18991 St. Paul MN",
        Library_Geolocation__c: { latitude: 44.96373, longitude: -93.17563 },
        List_As_Name__c: "Sharon Severson",
        Official_Charter_Number__c: "18991",
        Exact_Location_on_Map__c: true,
        Email_on_Map__c: false,
        Street__c: "1782 Englewood ave",
        City__c: "St. Paul",
        State_Province_Region__c: "MN",
        Country__c: "United States",
        Postal_Zip_Code__c: "55104",
        Id: "a06d000000l2YiGAAU",
    },
    {
        Library_Name__c: "Ron Wolfe #32090 St. Paul MN",
        Library_Geolocation__c: { latitude: 44.94364, longitude: -93.14237 },
        Official_Charter_Number__c: "32090",
        Library_Story__c: "I was leaving my house when a car drove by slowly. The woman in the car said she was researching a Minnesota children's author named Emma Brock who had lived in our building in the early 20th century. She was doing research to write a scholarly article about her.\n" +
            "I googled Emma Brock and discovered that she wrote and illustrated over 30 children's books. I ordered some on line for my wife who suggested building a Little Free Library in her honor!\n" +
            "We made the library look like our 5 unit condo!",
        Exact_Location_on_Map__c: true,
        Email_on_Map__c: false,
        Street__c: "998 Ashland Ave. #3",
        City__c: "St. Paul",
        State_Province_Region__c: "MN",
        Country__c: "United States",
        Postal_Zip_Code__c: "55104",
        Id: "a06d000000l4fffAAA",
    },
    {
        Library_Name__c: "Linda Walther #35950 Saint Paul MN",
        Library_Geolocation__c: { latitude: 44.94469, longitude: -93.14205 },
        Official_Charter_Number__c: "35950",
        Exact_Location_on_Map__c: false,
        Email_on_Map__c: false,
        Id: "a06d000000nQ5YCAA0",
    },
    {
        Library_Name__c: "Larissa Kiel #38651 Saint Paul MN",
        Library_Geolocation__c: { latitude: 44.94721, longitude: -93.15339 },
        Official_Charter_Number__c: "38651",
        Library_Story__c: "This library was a house warming gift from our wonderful cousins. Our family has always enjoyed finding Little Free Libraries around our community and seeing what treasures they hold. So to be gifted one of our very own was just brilliant. We are very appreciative of our cousins' thoughtfulness and generosity. It has made our new home even more magical!",
        Exact_Location_on_Map__c: true,
        Email_on_Map__c: false,
        Street__c: "1260 Dayton Ave",
        City__c: "Saint Paul",
        State_Province_Region__c: "MN",
        Country__c: "United States",
        Postal_Zip_Code__c: "55104",
        Id: "a06d000000pWmfGAAS",
    },
    {
        Library_Name__c: "Sarah Palkowitsch #40549 Saint Paul MN",
        Library_Geolocation__c: { latitude: 44.96453, longitude: -93.15043 },
        Official_Charter_Number__c: "40549",
        Exact_Location_on_Map__c: true,
        Email_on_Map__c: false,
        Street__c: "1190 Seminary Ave",
        City__c: "Saint Paul",
        State_Province_Region__c: "MN",
        Country__c: "United States",
        Postal_Zip_Code__c: "55104",
        Id: "a06d000000pXQ39AAG",
    },
    {
        Library_Name__c: "Danette Parr #1223 St Paul MN",
        Library_Geolocation__c: { latitude: 44.9429, longitude: -93.13276 },
        Official_Charter_Number__c: "1223",
        Library_Story__c: "We built the library as a family for two reasons:\n" +
            "1) We are part of an amazing neighborhood and wanted to give something to our community.\n" +
            "2) We understand the value of life long learning and how books encourage that... Holding a book in your hands and opening your mind to what it provides is special at any age.  There is something magical about sharing books with others.  \n" +
            "Happy Reading!  - The Parr's",
        Exact_Location_on_Map__c: true,
        Email_on_Map__c: false,
        Street__c: "774 Holly Avenue",
        City__c: "St Paul",
        State_Province_Region__c: "MN",
        Country__c: "United States",
        Postal_Zip_Code__c: "55104",
        Id: "a06d000000qvBPQAA2",
    },
    {
        Library_Name__c: "Audrey Olson #18944 St. Paul MN",
        Library_Geolocation__c: { latitude: 44.95255, longitude: -93.20126 },
        List_As_Name__c: "Audrey Olson",
        Official_Charter_Number__c: "18944",
        Library_Story__c: "My three sons surprised me on my 80th birthday by building my Little Free Library -- an accurate replica of the Olson family home in St. Paul where we lived for 50 years until we sold it last year. Although my new home faces Mississippi River Boulevard, parking there is forbidden, so we have placed the LFL at the back of the property facing Otis Avenue.  Come, see, enjoy a book!",
        Exact_Location_on_Map__c: true,
        Email_on_Map__c: false,
        Street__c: "409 Otis Avenue",
        City__c: "St. Paul",
        State_Province_Region__c: "MN",
        Country__c: "United States",
        Postal_Zip_Code__c: "55104",
        Id: "a06d000000sLaEHAA0",
    },
    {
        Library_Name__c: "James Hammar #4073 St. Paul MN",
        Library_Geolocation__c: { latitude: 44.94599, longitude: -93.16947 },
        Official_Charter_Number__c: "4073",
        Exact_Location_on_Map__c: false,
        Email_on_Map__c: false,
        Id: "a06d000000bUqt5AAC",
    },
]));
